-- Esquema inicial del Sprint 1: una tabla por responsabilidad, sin claves foráneas
-- entre módulos. La correlación es por tracking_number como identificador de negocio.

create table shipments (
    id bigint generated by default as identity,
    tracking_number varchar(255) not null unique,

    sender_full_name varchar(255) not null,
    sender_document_id varchar(255) not null,
    sender_phone varchar(255) not null,
    sender_address varchar(255) not null,
    sender_city varchar(255) not null,

    recipient_full_name varchar(255) not null,
    recipient_document_id varchar(255) not null,
    recipient_phone varchar(255) not null,
    recipient_address varchar(255) not null,
    recipient_city varchar(255) not null,

    description varchar(255) not null,
    status varchar(255) not null,
    registered_at timestamp(6) with time zone not null,

    last_movement_point varchar(255),
    last_movement_at timestamp(6) with time zone,

    primary key (id)
);

create table logistics_events (
    id bigint generated by default as identity,
    event_id varchar(255) not null unique,
    tracking_number varchar(255) not null,
    type varchar(255) not null,
    point varchar(255) not null,
    notes varchar(255),
    registered_at timestamp(6) with time zone not null,
    primary key (id)
);

-- Proyección local de logistics: los envíos que este módulo conoce.
create table logistics_tracked_shipments (
    tracking_number varchar(255) not null,
    registered_at timestamp(6) with time zone not null,
    primary key (tracking_number)
);

-- Modelo de lectura de reports: solo los datos que el cliente puede ver.
create table reports_shipment_tracking (
    tracking_number varchar(255) not null,
    status varchar(255) not null,
    recipient_name varchar(255) not null,
    destination_city varchar(255) not null,
    registered_at timestamp(6) with time zone not null,
    last_movement_point varchar(255),
    last_movement_at timestamp(6) with time zone,
    primary key (tracking_number)
);

create index idx_logistics_events_tracking_number on logistics_events (tracking_number);
