-- La ciudad de origen y destino era texto libre, así que "Bogotá", "Bogota" y
-- "Bogotá D.C." eran tres ciudades distintas para el sistema. Con eso no se puede
-- saber cuántos envíos van a una ciudad, ni determinar cobertura, ni evitar que un
-- error de digitación mande un paquete a ninguna parte.
--
-- Se introduce un catálogo de municipios con identificador propio. No se usa el
-- código DANE: solo aportaría al interoperar con facturación electrónica o con otra
-- transportadora, y obligaría a cargar y mantener correctos los 1.122 códigos
-- oficiales. La pareja nombre + departamento ya identifica el municipio sin
-- ambigüedad. Si más adelante hace falta, el código DANE entra como columna
-- nullable y única sin tocar nada de lo demás.
--
-- El envío guarda únicamente el identificador. Repetir nombre y departamento en el
-- envío sería una dependencia transitiva y rompería 3NF.

create table cities (
    id bigint generated by default as identity,
    name varchar(120) not null,
    department varchar(120) not null,
    primary key (id),
    constraint uk_cities_name_department unique (name, department)
);

-- El autocompletado busca por nombre.
create index idx_cities_name on cities (name);

-- Subconjunto de referencia: las 32 capitales de departamento, Bogotá y los
-- municipios de mayor volumen. Los demás se añaden con una migración nueva a medida
-- que la operación abra cobertura.
insert into cities (name, department) values
    ('MEDELLÍN', 'ANTIOQUIA'),
    ('APARTADÓ', 'ANTIOQUIA'),
    ('BELLO', 'ANTIOQUIA'),
    ('ENVIGADO', 'ANTIOQUIA'),
    ('ITAGÜÍ', 'ANTIOQUIA'),
    ('RIONEGRO', 'ANTIOQUIA'),
    ('BARRANQUILLA', 'ATLÁNTICO'),
    ('MALAMBO', 'ATLÁNTICO'),
    ('SOLEDAD', 'ATLÁNTICO'),
    ('BOGOTÁ', 'CUNDINAMARCA'),
    ('CARTAGENA DE INDIAS', 'BOLÍVAR'),
    ('TUNJA', 'BOYACÁ'),
    ('DUITAMA', 'BOYACÁ'),
    ('SOGAMOSO', 'BOYACÁ'),
    ('MANIZALES', 'CALDAS'),
    ('FLORENCIA', 'CAQUETÁ'),
    ('POPAYÁN', 'CAUCA'),
    ('VALLEDUPAR', 'CESAR'),
    ('MONTERÍA', 'CÓRDOBA'),
    ('CAJICÁ', 'CUNDINAMARCA'),
    ('CHÍA', 'CUNDINAMARCA'),
    ('FUNZA', 'CUNDINAMARCA'),
    ('FUSAGASUGÁ', 'CUNDINAMARCA'),
    ('GIRARDOT', 'CUNDINAMARCA'),
    ('MOSQUERA', 'CUNDINAMARCA'),
    ('SOACHA', 'CUNDINAMARCA'),
    ('ZIPAQUIRÁ', 'CUNDINAMARCA'),
    ('QUIBDÓ', 'CHOCÓ'),
    ('NEIVA', 'HUILA'),
    ('RIOHACHA', 'LA GUAJIRA'),
    ('SANTA MARTA', 'MAGDALENA'),
    ('VILLAVICENCIO', 'META'),
    ('PASTO', 'NARIÑO'),
    ('CÚCUTA', 'NORTE DE SANTANDER'),
    ('ARMENIA', 'QUINDÍO'),
    ('PEREIRA', 'RISARALDA'),
    ('DOSQUEBRADAS', 'RISARALDA'),
    ('BUCARAMANGA', 'SANTANDER'),
    ('BARRANCABERMEJA', 'SANTANDER'),
    ('FLORIDABLANCA', 'SANTANDER'),
    ('GIRÓN', 'SANTANDER'),
    ('PIEDECUESTA', 'SANTANDER'),
    ('SINCELEJO', 'SUCRE'),
    ('IBAGUÉ', 'TOLIMA'),
    ('CALI', 'VALLE DEL CAUCA'),
    ('BUENAVENTURA', 'VALLE DEL CAUCA'),
    ('PALMIRA', 'VALLE DEL CAUCA'),
    ('YUMBO', 'VALLE DEL CAUCA'),
    ('ARAUCA', 'ARAUCA'),
    ('YOPAL', 'CASANARE'),
    ('MOCOA', 'PUTUMAYO'),
    ('SAN ANDRÉS', 'ARCHIPIÉLAGO DE SAN ANDRÉS'),
    ('LETICIA', 'AMAZONAS'),
    ('INÍRIDA', 'GUAINÍA'),
    ('SAN JOSÉ DEL GUAVIARE', 'GUAVIARE'),
    ('MITÚ', 'VAUPÉS'),
    ('PUERTO CARREÑO', 'VICHADA');

alter table shipments add column sender_city_id bigint;
alter table shipments add column recipient_city_id bigint;

-- Las filas existentes traen el nombre escrito a mano. Se resuelve comparando sin
-- tildes ni mayúsculas contra el catálogo.
update shipments s
set sender_city_id = c.id
from cities c
where upper(translate(s.sender_city, 'áéíóúüñÁÉÍÓÚÜÑ', 'aeiouunAEIOUUN'))
      = upper(translate(c.name, 'áéíóúüñÁÉÍÓÚÜÑ', 'aeiouunAEIOUUN'));

update shipments s
set recipient_city_id = c.id
from cities c
where upper(translate(s.recipient_city, 'áéíóúüñÁÉÍÓÚÜÑ', 'aeiouunAEIOUUN'))
      = upper(translate(c.name, 'áéíóúüñÁÉÍÓÚÜÑ', 'aeiouunAEIOUUN'));

-- Lo que no se pudo resolver detiene la migración en lugar de inventarle una ciudad.
-- Si esto falla, el mensaje dice qué valores no están en el catálogo: hay que
-- añadirlos al catálogo o corregir esas filas antes de volver a migrar.
do $$
declare
    sin_resolver text;
begin
    select string_agg(distinct ciudad, ', ')
    into sin_resolver
    from (
        select sender_city as ciudad from shipments where sender_city_id is null
        union
        select recipient_city as ciudad from shipments where recipient_city_id is null
    ) pendientes;

    if sin_resolver is not null then
        raise exception 'Ciudades que no están en el catálogo: %', sin_resolver;
    end if;
end $$;

alter table shipments alter column sender_city_id set not null;
alter table shipments alter column recipient_city_id set not null;

-- El catálogo es dato de referencia, no de otro módulo de negocio: la clave foránea
-- aquí no acopla módulos, garantiza que no exista un envío hacia una ciudad que no
-- está en el catálogo.
alter table shipments add constraint fk_shipments_sender_city
    foreign key (sender_city_id) references cities (id);
alter table shipments add constraint fk_shipments_recipient_city
    foreign key (recipient_city_id) references cities (id);

alter table shipments drop column sender_city;
alter table shipments drop column recipient_city;

-- El modelo de lectura sí guarda la etiqueta que ve el cliente
-- ("MEDELLÍN - ANTIOQUIA") junto con el identificador. Ahí la duplicación es
-- intencional y es la razón de ser de la proyección: responder la consulta sin unir
-- tablas.
alter table reports_shipment_tracking add column destination_city_id bigint;

update reports_shipment_tracking r
set destination_city_id = c.id,
    destination_city = c.name || ' - ' || c.department
from shipments s
    join cities c on c.id = s.recipient_city_id
where s.tracking_number = r.tracking_number;

-- Una proyección puede tener filas que ya no existan como envío; se reconstruye con
-- POST /api/admin/reconstruir-proyecciones en lugar de bloquear la migración.
delete from reports_shipment_tracking where destination_city_id is null;

alter table reports_shipment_tracking alter column destination_city_id set not null;
